ci:
  - changed-files:
      - any-glob-to-any-file: .github/**/*

docs:
  - changed-files:
      - any-glob-to-any-file: packages/docs/*

app:
  - changed-files:
      - any-glob-to-any-file: packages/app/*

studio:
  - changed-files:
      - any-glob-to-any-file: packages/studio/*
