name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

  merge_group:
    types: [checks_requested] # Trigger when pull request is synchronized or closed

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Load environment variables from .env file
        run: |
          cd ./packages/app
          cp .env.example .env

      - name: Run tests
        run: bun run test:app
